//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Management.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class datAcademician
    {
        public int AcID { get; set; }
        public string AcFirstName { get; set; }
        public string AcLastName { get; set; }
        public string Title { get; set; }
        public string AcNo { get; set; }
        public string AcPass { get; set; }
    }
}
