//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Management.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class datStudent
    {
        public int StudentID { get; set; }
        public string StudentFirstName { get; set; }
        public string StudentLastName { get; set; }
        public string StudentNo { get; set; }
        public string StudentPass { get; set; }
        public string StudentMail { get; set; }
        public string StudentImg { get; set; }
        public Nullable<int> StudentDep { get; set; }
    
        public virtual datDepartment datDepartment { get; set; }
    }
}
