//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Management.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class universityDbEntities2 : DbContext
    {
        public universityDbEntities2()
            : base("name=universityDbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<datAcademician> datAcademician { get; set; }
        public virtual DbSet<datDepartment> datDepartment { get; set; }
        public virtual DbSet<datLessons> datLessons { get; set; }
        public virtual DbSet<datStudent> datStudent { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<datGrades> datGrades { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
    }
}
