//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Management.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class universityDbEntities2 : DbContext
    {
        public universityDbEntities2()
            : base("name=universityDbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<datAcademician> datAcademician { get; set; }
        public virtual DbSet<datDepartment> datDepartment { get; set; }
        public virtual DbSet<datLessons> datLessons { get; set; }
        public virtual DbSet<datStudent> datStudent { get; set; }
        public virtual DbSet<datGrades> datGrades { get; set; }
    
        public virtual ObjectResult<Grades_Result> Grades()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Grades_Result>("Grades");
        }
    
        public virtual ObjectResult<StudentGrades_Result> StudentGrades()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudentGrades_Result>("StudentGrades");
        }
    
        public virtual ObjectResult<StudentGradess_Result> StudentGradess()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StudentGradess_Result>("StudentGradess");
        }
    
        public virtual ObjectResult<StGrade_Result> StGrade()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StGrade_Result>("StGrade");
        }
    
        public virtual ObjectResult<StGrades_Result> StGrades()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StGrades_Result>("StGrades");
        }
    
        public virtual ObjectResult<StGrades2_Result> StGrades2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StGrades2_Result>("StGrades2");
        }
    
        public virtual ObjectResult<StGrades3_Result> StGrades3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StGrades3_Result>("StGrades3");
        }
    
        public virtual ObjectResult<StGrades4_Result> StGrades4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StGrades4_Result>("StGrades4");
        }
    
        public virtual ObjectResult<StGrades5_Result> StGrades5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StGrades5_Result>("StGrades5");
        }
    }
}
